/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sp6mybatis.pro1;


import java.util.List;
import java.util.Map;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import org.apache.ibatis.session.SqlSession;

// import org.apache.logging.log4j.core.Logger;
// import org.slf4j.Logger;
// import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import com.sp6mybatis.pro1.config.ControllerConfig;
import com.sp6mybatis.pro1.config.DBConfig;
import com.sp6mybatis.pro1.config.DaoConfig;
import com.sp6mybatis.pro1.config.ServiceConfig;
import com.sp6mybatis.pro1.dto.system.common.CommonCodeDTO;
import com.sp6mybatis.pro1.dto.system.common.RegionCodeDTO;
import com.sp6mybatis.pro1.service.education.EducationSearchService;
import com.sp6mybatis.pro1.service.system.common.CommonCodeService;


public class App {

    private static final Logger logger = LogManager.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext(ServiceConfig.class, DaoConfig.class, DBConfig.class, ControllerConfig.class);
        
        // logger.debug("DEBUG...");
        // logger.info("INFO...");
        // logger.error("ERROR....");
        // Map<String, SqlSession> map = ctx.getBeansOfType(SqlSession.class);
        // System.out.println(map.keySet());
        
        CommonCodeService svc2 = ctx.getBean("commonCodeService", CommonCodeService.class);
        RegionCodeDTO dto = new RegionCodeDTO();
        dto.addParam("q_LV", "LV3");
        dto.setUpRegionCode("1129000000");
        

        List<RegionCodeDTO> l = svc2.selectRegionCombo(dto);
        System.out.println(l);

        ctx.close();
    }
}
